package com.wills.help.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wills.help.db.bean.Contact;
import com.wills.help.db.bean.PointInfo;
import com.wills.help.db.bean.OrderTypeInfo;

import com.wills.help.db.dao.ContactDao;
import com.wills.help.db.dao.PointInfoDao;
import com.wills.help.db.dao.OrderTypeInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig pointInfoDaoConfig;
    private final DaoConfig orderTypeInfoDaoConfig;

    private final ContactDao contactDao;
    private final PointInfoDao pointInfoDao;
    private final OrderTypeInfoDao orderTypeInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        pointInfoDaoConfig = daoConfigMap.get(PointInfoDao.class).clone();
        pointInfoDaoConfig.initIdentityScope(type);

        orderTypeInfoDaoConfig = daoConfigMap.get(OrderTypeInfoDao.class).clone();
        orderTypeInfoDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        pointInfoDao = new PointInfoDao(pointInfoDaoConfig, this);
        orderTypeInfoDao = new OrderTypeInfoDao(orderTypeInfoDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(PointInfo.class, pointInfoDao);
        registerDao(OrderTypeInfo.class, orderTypeInfoDao);
    }
    
    public void clear() {
        contactDaoConfig.clearIdentityScope();
        pointInfoDaoConfig.clearIdentityScope();
        orderTypeInfoDaoConfig.clearIdentityScope();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public PointInfoDao getPointInfoDao() {
        return pointInfoDao;
    }

    public OrderTypeInfoDao getOrderTypeInfoDao() {
        return orderTypeInfoDao;
    }

}
